### ISSUE TITLE
Undefined function or variable 'hogPatches'.

### ISSUE THREAD

**Issue by lgbwust** [jacobgil/BagOfVisualWords#1]
Hi, when I run train.m, an error occured,
patches = hogPatches(img, frames', patchSize, blockSize);
There is not a function names hogPatches, how to solve it? Thanks!!!

**Comment by jacobgil** [comment]
Hi, thanks for posting this issue.
hogPatches.m was missing, added it now.

Can you confirm it works?

**Comment by lgbwust** [comment]
@jacobgil Thanks, now it can work well.
